shopCart/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'shopCart.views.home', name='home'),
    url(r'^$', 'shopicart.views.login_view', name='login_view'),
    url(r'^shopicart/',include('shopicart.urls',namespace="shopicart")),
    url(r'^admin/', include(admin.site.urls)),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)	

urlpatterns += staticfiles_urlpatterns()

shopicart/urls.py
from django.conf.urls import patterns, url

from shopicart import views
 #url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^home/$', views.home, name='home'),
    url(r'^logincheck/$', views.logincheck, name='logincheck'),   
    url(r'^logout/$', views.logout_view, name='logout_view'),
   # url(r'^home/category/(?\D)+/$', views.category, name='category'),
    url(r'^home/category/(?P<category_id>\d+)/$', views.category, name='category'),
    url(r'^home/userCart/(?P<user_id>\d+)/$', views.mycart, name='mycart'),
   # url(r'^home/userCart/$', views.mycartblank, name='mycartblank'),
    url(r'^home/addcart/(?P<product_id>\d+)/$', views.addcart, name='addcart'),
    url(r'^home/userCart/(?P<user_id>\d+)/removecart/(?P<product_id>\d+)/$', views.removecart, name='removecart'),
    url(r'^home/userCart/(?P<user_id>\d+)/checkout/$', views.checkout, name='checkout'),
    url(r'^home/userCart/(?P<user_id>\d+)/payamount/$', views.payamount, name='payamount'),
    url(r'^home/userCart/(?P<user_id>\d+)/history/$', views.history, name='history'),
   # url(r'^home/userCart/(?P<user_id>\d+)/history/removehistory/(?P<product_id>\d+)/$', views.removehistory, name='removehistory'),
   # url(r'^home/userCart/(?P<user_id>\d+)/history/removehistoryall/$', views.removehistoryall, name='removehistoryall'),
    url(r'^home/search/$', views.search, name='search'),
    url(r'^home/userCart/(?P<user_id>\d+)/history/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/historydel/$', views.historydel, name='historydel'),
    url(r'^myexp/$',views.myexp,name='myexp')
    )

shopicart/models.py
from django.db import models
from sorl.thumbnail import ImageField, get_thumbnail
from PIL import Image, ImageOps
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from datetime import datetime

class Category(models.Model):
  category = models.CharField(max_length=100,unique=True) 
  def __str__(self):
    return self.category

class Products(models.Model):
  title = models.CharField(max_length=100)
  description = models.CharField(max_length=300)
  price = models.DecimalField(max_digits=15,decimal_places=2)
  Category = models.ForeignKey(Category) 
  image = models.ImageField(upload_to="images/",blank=False, null=True,editable=True)
  add_date = models.DateTimeField(auto_now_add=True)
  modified_date = models.DateTimeField(auto_now=True)

  def __str__(self):
    return self.title

  def slide_thumbnail(self):
    if self.image:
      return '<img src="/%s" />' % self.image.url
  slide_thumbnail.short_description = 'Image'
  slide_thumbnail.allow_tags = True

class UserCart(models.Model):
  user = models.ForeignKey(User,null=True)  
  product = models.ForeignKey(Products)
  add_date = models.DateField(auto_now_add=True,default=datetime.now())
  qty = models.IntegerField(max_length=2,default=1)


class History(models.Model):
  pur_date = models.DateField(auto_now_add=True,default=datetime.now())
  user = models.ForeignKey(User,null=True)
  title = models.CharField(max_length=100,null=True)
  price = models.DecimalField(max_digits=15,decimal_places=2)
  image = models.ImageField(upload_to="images/",blank=False, null=True,editable=True)
  qty = models.IntegerField(max_length=2,default=1)
  def __str__(self):
    return self.title

shopicart/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect,HttpResponse
from shopicart.models import Products, UserCart, Category, History
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from datetime import datetime

# Create your views here.

def myexp(request):
  values = {'Title':'mytitle','userid':'2','username':'Jhon'}
  context = {'content':values}
  return render(request,'shopicart/child.html',context)

def index(request):
  context = {}
  return render(request, 'shopicart/index.html',context)

def login_view(request):
  context = {}
  return render(request,'shopicart/index.html',context)

def logincheck(request):
  if request.method == 'POST':
    uid = request.POST.get('id')
    upass = request.POST.get('password')
    user = authenticate(username=uid,password=upass)
    if user is not None:   #for pass is not valid
      login(request,user)
      request.session['username'] = user.first_name
      request.session['userid'] = user.id
      return  HttpResponseRedirect('/shopicart/home/')
    else:
      context = {'message' : 'Username and password is not matched.. '}
      return render(request, 'shopicart/index.html',context)
  else:
    context = {}
    return render(request,'shopicart/index.html',context)


def register(request):
  context = {}
  if request.method == 'POST':
    try:
      context = {}
      uname= request.POST.get('uid')
      uemail= request.POST.get('id')
      upass = request.POST.get('password')
      user = User.objects.create_user(uemail,uemail,upass)
      user.first_name = uname
      user.save()
      user = authenticate(username=uemail,password=upass)
      login(request,user)
      request.session['username'] = user.first_name
      request.session['userid'] = user.id
      print request.session.get('userid')
      return HttpResponseRedirect('/shopicart/home/')
    except Exception, e:
      context = {'message':'Mail id already exist'}
      return render(request,'shopicart/register.html',context)
  else:
    return render(request, 'shopicart/register.html',context)

@login_required
def home(request):
  #if request.user.is_authenticated():
    products = Products.objects.all()
    category = Category.objects.all()
    context = {'userid':request.session.get('userid'),'media':'/media/','product': products,'username': request.session.get('username'),'products': products,'category':category}
    if request.GET.get('msg'):
      msg = request.GET.get('msg')
      context['message'] = msg
    if request.GET.get('search'): 
      search = request.GET.get('search')
      products = Products.objects.filter(title__icontains=search)
      context['products'] = products
    return render(request, 'shopicart/homec.html',context)

@login_required
def logout_view(request): 
  context = {}
  request.session['logon'] = 'false'
  request.session['username'] = 'None'
  request.session['userid'] = '0'
  logout(request)
  return render(request,'shopicart/logout.html',context)

@login_required
def category(request,category_id):
  context = {'username':request.session.get('username')}
  products = Products.objects.filter(Category_id=category_id)
  category = Category.objects.all()
  context = {'media':'/media/','username': request.session.get('username'),'products': products,'category':category,'userid':request.session.get('userid')}
  return render(request,'shopicart/home.html',context)

@login_required
def mycart(request,user_id):
  poList = []
  productid = UserCart.objects.filter(user_id=int(user_id))  
  for pid in productid:
    poList.append(Products.objects.get(pk=pid.product_id))
  if not poList:
    msg = 'Cart is empty'
  elif request.GET.get('msg'):
    msg = request.GET.get('msg')
  else:
    msg = ''
  context = {'ucobj':productid,'message':msg,'products':poList,'media':'/media/','username':request.session.get('username'),'userid':request.session.get('userid')}
  return render(request,'shopicart/mycartc.html',context)

@login_required
def addcart(request,product_id):
  objc = UserCart.objects.filter(user_id=request.session.get('userid'))
  notFound = 'True'
  for obj in objc:
    if obj.product_id == int(product_id):
      obj.qty = obj.qty + 1
      obj.save()
      notFound = ''
      break
  if notFound:
    objuc = UserCart(user_id=request.session.get('userid'),product_id=product_id)
    objuc.save()
  obj= Products.objects.get(id=product_id)
  context = {'message':obj.title+' add to cart successfully'}
  return HttpResponseRedirect('/shopicart/home/?msg='+obj.title+' add to cart successfully')
    #return HttpResponseRedirect('/shopicart/home/')
    #return render(request,'shopicart/redirect.html',context)

@login_required
def removecart(request,user_id,product_id):
  productid = UserCart.objects.filter(user_id=int(user_id))
  for pid in productid:
    if pid.product_id == int(product_id):
      if pid.qty > 1:
        pid.qty = pid.qty - 1
        pid.save()
      else:
        pid.delete()
      break
  obj = Products.objects.get(id=product_id)
  message = obj.title+' remove from cart'
  #return HttpResponseRedirect(reverse('shopicart:mycart',kwargs=context))
  return HttpResponseRedirect('/shopicart/home/userCart/'+user_id+'/?msg='+message)
  #return render(request,'shopicart/removecart.html',context)

@login_required
def checkout(request,user_id):
  total = 0
  poList = []
  pList = []
  msg = ''
  productid = UserCart.objects.filter(user_id=int(user_id))  
  for pid in productid:
    obj = Products.objects.get(pk=pid.product_id)
    total = total + (obj.price*pid.qty)
    poList.append(Products.objects.get(pk=pid.product_id)) 
  if not poList:
    msg = 'No products in checkout'
  context = {'ucobj':productid,'message':msg,'total':total,'products':poList,'media':'/media/','username':request.session.get('username'),'userid':request.session.get('userid')}
  return render(request,'shopicart/checkoutc.html',context)

@login_required
def payamount(request,user_id):
  productid = UserCart.objects.filter(user_id=int(user_id))
  for upid in productid:
    pid = Products.objects.get(id=upid.product_id)
    obj = History(qty=upid.qty,pur_date=datetime.now(),user_id=user_id,title=pid.title,price=pid.price*upid.qty,image=pid.image)
    obj.save()
    upid.delete()
  #context = {'msg':'Products purchased successfully'}
  return HttpResponseRedirect('/shopicart/home/?msg=Products purchased successfully')
  #return render(request,'shopicart/amountpaid.html',context)

#@login_required
#def history(request,user_id):
  #msg = ''
  #products = History.objects.filter(user_id=int(user_id))  
  #if request.GET.get('msg'):
    #msg = request.GET.get('msg') 
  #if not products:
    #msg = 'No item in history'
  #context = {'message':msg,'products':products,'media':'/media/','username':request.session.get('username'),'userid':request.session.get('userid')}
  #return render(request,'shopicart/historyc.html',context)

@login_required
def history(request,user_id):
  msg = ''
  date = []
  total =0
  msg = 'History'
  products = History.objects.filter(user_id=int(user_id))  
  if request.GET.get('msg'):
    msg = request.GET.get('msg') 
  if not products:
    msg = 'No item in history'
  for product in products:
    date.append(product.pur_date)
    total = product.price + total
  date = list(set(date))
  context = {'total':total,'dates':date,'message':msg,'products':products,'media':'/media/','username':request.session.get('username'),'userid':request.session.get('userid')}
  return render(request,'shopicart/historyc.html',context)

"""
@login_required
def removehistory(request,user_id ,product_id):
  prod_obj = History.objects.get(id=product_id)
  msg = prod_obj.title+' remove from history'
  prod_obj.delete()
  return HttpResponseRedirect('/shopicart/home/userCart/'+user_id+'/history/?msg='+msg)


@login_required
def removehistoryall(request,user_id):
  productid = History.objects.filter(user_id=int(user_id))
  for pid in productid:
    pid.delete()
  context = {'userid':user_id}
  return HttpResponseRedirect('/shopicart/home/userCart/'+user_id+'/history/')
"""

@login_required
def search(request):
  search = request.POST.get('search')
  if search == '':
    return HttpResponseRedirect('/shopicart/home/')
  else:
    return HttpResponseRedirect('/shopicart/home/?search='+search)

@login_required
def historydel(request,user_id,year,month,day):
  prod_obj = History.objects.filter(user_id=user_id)
  for obj in prod_obj:
    if obj.pur_date.day == int(day) and obj.pur_date.month == int(month) and obj.pur_date.year == int(year):
      print obj.delete()
  msg = 'History removed of date :'+day+'/'+month+'/'+year
  return HttpResponseRedirect('/shopicart/home/userCart/'+user_id+'/history/?msg='+msg)

shopicart/templates/shopicart/amountpaid.html
<p>
	{{ message }}
	 <p> <a href="{% url 'shopicart:home'  %}">Click Here </a> to continue shopping</p> 
</p>

shopicart/templates/shopicart/base.html
{% load staticfiles %} 
{% load mathfilters %}
<html>
<head>
    <title>{% block title %} Shopping cart {% endblock %}</title>
</head>
<body>
{% block header %}{% endblock %}<br />
{% block messages %}{% endblock%}
{% block mainblock %}{% endblock %}
<link rel="stylesheet" type="text/css" href="{% static "shopicart/css/table.css" %}" />
<script type="text/javascript" src={% static "shopicart/js/validation.js" %}></script>
<script type="text/javascript" src={% static "shopicart/js/confirmmsg.js" %}></script>
</body>
</html>

shopicart/templates/shopicart/checkoutc.html
{% extends "shopicart/base.html" %}
{% block header %}
{% include "shopicart/header.html" %}
{% endblock %}
{% load mathfilters %}
{% block messages %}
  {{ message }}
{% endblock %}

{% block  mainblock %}
 <table width="100%" align="center" border="0" bgcolor="E6E6E6">
 <hr /><br />
    {% for product in products %}
	<table width="100%">
       <tr>
                <td class="tableImg">
                   <img src = {{media}}{{ product.image }} height="100" width="100"></td>
                  <td class="tableDec"> <p><b>Title : <b>{{ product.title|capfirst }}</p>
                   <p> <b>Description :</b>{{ product.description|capfirst }}</p>
                   </td>
                   {% for objuc in ucobj %}
                   {% if objuc.product_id == product.id %}
                   <td>
                     <p><b>Qty: {{ objuc.qty }}</b></p>
                   </td> 
                    <td class="tableDate"><p> <b>Price :</b>{{ product.price|mul:objuc.qty }}</p></td>
                   {% endif %}
                   {% endfor %}
         </tr>
    </table>
     <hr/>
     {% endfor %}
</table>
     {% if total  %}
            <h4 align="right"> <p>Total Amount  = {{ total }}</p></h4> 
            <h1 align="right"><a href="{% url 'shopicart:payamount' userid %}"><button onclick="return myFunction({{total}}) " >Go for payment</button></a>  </h1>
     {% endif %}
{% endblock %}

shopicart/templates/shopicart/header.html
<html>
<body>
<h3 align="center"> <header>Welcome to the Shopping Cart</header> </h3> 
<hr align="center">
<table width="100%" align="center">
  <tr>
    <th align="left" width="40%">   
      <p>
      <a href="/shopicart/home/">Back</a>
      <a href="/shopicart/home/">Home</a> 
      <a href="/shopicart/home/userCart/{{ userid }}/history/">History</a>   
      <a href="/shopicart/home/userCart/{{ userid }}/checkout/">Checkout</a>      
      </p>
    </th>
    <th align="right" width="60%">
      <p>Welcome, {{ username }} <a href="/shopicart/logout/">Logout</a></p> 
    </th>
  </tr>
</table>
</body>
</html>

shopicart/templates/shopicart/historyc.html
{% extends "shopicart/base.html" %}
{% block header %}
{% include "shopicart/header.html" %}
{% endblock %}

{% block messages %}
  <p>{{ message }}</p>
{% endblock %}

{% block mainblock %}
<form id="historyform">
{% csrf_token %}
 <table width="100%" align="center" border="0" bgcolor="E6E6E6">
 <hr /><br />
  {% for date in dates %}
  <tr align="left"><h4>Order date :{{ date }}</h4></tr>
    {% for product in products %}
       {% if date == product.pur_date %}
	<table width="100%">
       <tr>
                <td class="tableImg">
                   <img src = {{media}}{{ product.image }} height="100" width="100"></td>
                  <td class="tableDec"> <p><b>Title : <b>{{ product.title|capfirst }}</p>
                  </td> 
                  <td class="tablePrice"><p> <b> Qty : {{ product.qty }}</b> </p></td>
                  <td class="tablePrice"><p> <b>Price :</b>{{ product.price|capfirst }}</p></td>
         </tr>
    </table>
       {% endif %}
    {% endfor %} 
      <h4 align="right">Total Amount : {{ total }}</h4>
      <h4 align="right"> <a href="{% url 'shopicart:historydel' userid date.year date.month date.day %}">Remove</a> </h4>
    <hr/>
  {% endfor %} 
  </table>
</form>
{% endblock %}

shopicart/templates/shopicart/home.html
<html> 
<head> 
<title>Shopping cart</title> 
</head>
{% load staticfiles %} 
<link rel="stylesheet" type="text/css" href="{% static "shopicart/css/table.css" %}" />
<body> 
{% csrf_token %}
<h3 align="center"> <header>Welcome to the Shopping Cart</header> </h3> 
<hr align="center">
<div align="right">
<p>Welcome, {{ username }}<a href="{% url 'shopicart:logout_view' %}">Logout</a></p>
</div>

 <a href="/shopicart/home/userCart/{{ userid }}/">View MyCart</a> 
 <h4 align="center"><p> {{ message|capfirst }} </p></h4> 
<form name="searchform" method="POST" action="{% url 'shopicart:search' %}">
{% csrf_token %}
 <input type="text" name="search"><button name="submit" type="submit">Search</button></form>
 
<table width="100%" border="0">
  <tr valign="top">
    <td width="10%" bgcolor="#D6D6F5">
      <h4 align="center"> <b>Catogery</b> </h4><br />
      <li><a href="{% url 'shopicart:home' %}"> All </a> </li>
      {% for product in category %}
         <li><a href="{% url 'shopicart:category' product.id %}"> {{ product|capfirst }} </a>
         </li>
      {% endfor %}  
    </td>
    <td bgcolor="E6E6E6" height="1200" width="60%">
       
          {% for product in products %}
            <table width="100%">
              <tr>
                <th align="center" width="20%">
                   <img src = {{media}}{{ product.image }} height="100" width="100"></th>
                  <th align="left" width="70%"> 
                  <p><b>Title : <b>{{ product.title|capfirst }}</p>
                   <p> <b>Price :</b>{{ product.price }}</p>
                   <p> <b>Discription :</b>{{ product.description|capfirst }}</p>
                   </th>        
                   <hr>
                   <th align="left" width="10%"><a href="{% url 'shopicart:addcart' product.id %}"><button>Add to Cart</button></a> </th> 
                 </tr>
            </table>
       {% endfor %}
    </td> 
   </tr>
<table>
</body>
</html>
</body>
</html>

shopicart/templates/shopicart/homec.html
{% extends "shopicart/base.html" %}

{% block header %}
{% include "shopicart/header.html" %}
{% endblock %}

{% block messages %}
{% include "shopicart/viewcart.html" %}
{% endblock %}

{% block mainblock %}
{% include "shopicart/homeform.html" %}
{% endblock %}	

shopicart/templates/shopicart/homeform.html
  <table width="100%" align="center" border="0">
    <tr valign="top">
    <td align="left " height="1200" width="15%" bgcolor="#D6D6F5">
      <h4 align="center"> <b>Catogery</b> </h4><br />
      <li><a href="{% url 'shopicart:home' %}"> All </a> </li>
      {% for product in category %}
         <li><a href="{% url 'shopicart:category' product.id %}"> {{ product|capfirst }} </a>
         </li>
      {% endfor %}
    </td>

    <td align="center" height="1200" width="85%" bgcolor="#E6E6E6"><hr />
    {% for product in products %}
    <table width="100%">
    <tr>
      <td class="tableImg">
        <img src = {{media}}{{ product.image }} height="100" width="100">
      </td>
      <td class="tableDec">
        <p><b>Title : <b>{{ product.title|capfirst }}</p>
        <p> <b>Price :</b>{{ product.price }}</p>
        <p> <b>Discription :</b>{{ product.description|capfirst }}</p>
      </td>
      <td class="tableLink">
        <a href="{% url 'shopicart:addcart' product.id %}"><button>Add to Cart</button></a>
      </td>
      </tr>
    </table>
    <hr />
       {% endfor %}
      </td>
    </tr>
  </table>

shopicart/templates/shopicart/index.html
{% load staticfiles %}
<script type="text/javascript" src={% static "shopicart/js/validation.js" %}>

function clearData(){
  document.getElementById('login').value = "";
  document.getElementById('password').value = "";
}
</script>

<body onload="clearData()">
 <form name="login"	action="{% url 'shopicart:logincheck' %}"  method="POST">
{% csrf_token %}
  Email ID :<br/>
  <input type="text" name="id">
  <br/>
  Password :<br/>
  <input type="password" name="password"><br /><br />
  <a href="{% url 'shopicart:register' %}">New user,Register here</a>
  <br /><br />
  <button type="submit" value="submit" onclick="return validateFormLogin(document.login.id.value,document.login.password.value)">Submit</button><br /><br />  
   <p> {{ message }} </p> 
</form> 
</body>

shopicart/templates/shopicart/logout.html
<h4><p>You are logged out. </p></h4>
<p><a href="/shopicart/">Click here</a> to login again</p>
	

shopicart/templates/shopicart/mycart.html
<html> 
<head> 
<title>Home</title> 
</head> 
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static "shopiart/css/table.css" %}" />
<body> 
{% csrf_token %}
<h3 align="center"> <header>Welcome to the Shopping Cart</header> </h4> 
<hr align="center">
<div align="right">
<p>Welcome, {{ username }} <a href="/shopicart/logout/">Logout</a></p> 
</div>
<p>
  <h3 align="left">Products in your   cart is</h3>
  <a href="/shopicart/home/">Back</a>
  <a href="/shopicart/home/">Home</a> 
  <a href="/shopicart/home/userCart/{{ userid }}/history/">History</a>   
  <a href="/shopicart/home/userCart/{{ userid }}/checkout/">Checkout</a> 
  <h3 align="center"><p>{{ message|capfirst }}</p></h3> 
  <hr>
</p>
<table width="100%" border="0">
  <tr valign="top">
    <td bgcolor="E6E6E6" height="1200" width="60%" align="center">
       {% for product in products %}
            <table width="100%">
              <tr>
                <th align="center" width="20%">
                   <img src = {{media}}{{ product.image }} height="100" width="100"></th>
                  <th align="left" width="60%"> <p><b>Title : <b>{{ product.title|capfirst }}</p>
                   <p> <b>Price :</b>{{ product.price|capfirst }}</p>
                   <p> <b>Description :</b>{{ product.description|capfirst }}</p>
                   </th> 
                   <th width="20%" align="center"><p><b>Date :</b>{{ product.add_date }}</p></th>
                   <hr>
                   <th align="left" width="10%"><a href="/shopicart/home/userCart/{{ userid }}/removecart/{{ product.id }}/">Remove</a> 
                  </th>            
       {% endfor %}         
              </tr>
            </table>
    </td> 
   </tr>
<table>

</body>
</html>

shopicart/templates/shopicart/mycartc.html
{% extends "shopicart/base.html" %}

{% block header %}
{% include "shopicart/header.html" %}
{% endblock %}

{% block messages %}
{{ message }}
{% endblock %}

{% block mainblock %}
{% include "shopicart/mycartform.html" %}
{% endblock %}

shopicart/templates/shopicart/register.html
{% load staticfiles %}

<script type="text/javascript" src={% static "shopicart/js/validation.js" %}>

</script>
<body>
 <form name="register"	action="/shopicart/register/" method="POST">
 {% csrf_token %}
  Name :<br/>
  <input type="text" name="uid">
  <br/>
  Email ID :<br/>
  <input type="text" name="id">
  <br/>
  Password :<br/>
  <input type="password" name="password"><br />
  Confirm password :<br />
  <input type="password" name="password1"><br /><br />

  <button type="submit" value="submit" onclick="return validateFormRegister(document.register.uid.value,document.register.id.value,document.register.password.value,document.register.password1.value)">Sign Up</button><br /><br />
   <p> {{ message }} </p> 
</form> 
</body>

shopicart/templates/shopicart/viewcart.html
 <form name="searchform" method="POST" action="{% url 'shopicart:search' %}">
 {% csrf_token %}
  <table width="100%">
    <tr>
      <td align="left" width="20%">
      <input type="text" name="search"><button name="submit" type="submit">Search</button> 
      </td>
      <td align="center" width="50%">
         <h4 align="center"><p> {{ message|capfirst }} </p></h4>  
      </td>
      <td align="right" width="10%">
        <a href="/shopicart/home/userCart/{{ userid }}/">View MyCart</a> 
      </td>
    </tr>
  </table>
 </form>